__title__ = 'xpdt'
__description__ = 'eXPeditious Data Transfer'
__url__ = 'https://github.com/giannitedesco/xpdt'
__author__ = 'Gianni Tedesco'
__author_email__ = 'gianni@scaramanga.co.uk'
__copyright__ = 'Copyright 2020 Gianni Tedesco'
__license__ = 'GPLv3'
__version__ = '0.0.3'
